version: '3.8'

services:
  # Frontend service
  frontend:
    image: kahaozeng/prestabanco-frontend:latest
    container_name: frontend-1
    ports:
      - "8070:80"
    depends_on:
      - backend
    networks:
      - app-network
    # Enviar logs directamente a Logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "frontend"

  # Backend service
  backend:
    image: kahaozeng/prestabanco-backend:latest
    container_name: backend-1
    environment:
      DB_HOST: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prestabanco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - app-network
    # Enviar logs directamente a Logstash
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "backend"

  # PostgreSQL 
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_DB: prestabanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana-1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

  # Logstash - Con entrada GELF para logs directos
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash-1
    ports:
      - "5044:5044"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    command: >
      bash -c "
      echo 'input { 
        gelf { port => 12201 }
      }
      filter {
        if [tag] {
          mutate { add_field => { \"service\" => \"%{[tag]}\" } }
        }
        mutate { add_field => { \"application\" => \"prestabanco\" } }
      }
      output {
        elasticsearch {
          hosts => [\"elasticsearch:9200\"]
          index => \"prestabanco-logs-%{+YYYY.MM.dd}\"
        }
        stdout { codec => dots }
      }' > /usr/share/logstash/pipeline/logstash.conf &&
      /usr/local/bin/docker-entrypoint
      "

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    external: true
  elasticsearch_data:
    driver: local