version: '3.8'

services:
  # Frontend service
  frontend:
    image: kahaozeng/prestabanco-frontend:latest
    container_name: frontend-1
    ports:
      - "8070:80"
    depends_on:
      - backend
    networks:
      - app-network
    # Logging directo a syslog para captura
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5514"
        tag: "frontend"

  # Backend service
  backend:
    image: kahaozeng/prestabanco-backend:latest
    container_name: backend-1
    environment:
      DB_HOST: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prestabanco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - app-network
    # Logging directo a syslog
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5514"
        tag: "backend"

  # PostgreSQL 
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_DB: prestabanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  # Elasticsearch - Base de datos de logs
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  # Kibana - Dashboard web
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana-1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

  # Logstash - Para capturar logs de aplicación
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash-1
    ports:
      - "5514:5514/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    command: >
      bash -c "
      echo 'input { 
        syslog { port => 5514 }
      }
      filter {
        if [program] == \"frontend\" {
          mutate { 
            add_field => { \"service\" => \"frontend\" }
            add_field => { \"application\" => \"prestabanco\" }
          }
        }
        if [program] == \"backend\" {
          mutate { 
            add_field => { \"service\" => \"backend\" }
            add_field => { \"application\" => \"prestabanco\" }
          }
        }
      }
      output {
        elasticsearch {
          hosts => [\"elasticsearch:9200\"]
          index => \"prestabanco-app-logs-%{+YYYY.MM.dd}\"
        }
        stdout { codec => dots }
      }' > /usr/share/logstash/pipeline/logstash.conf &&
      /usr/local/bin/docker-entrypoint
      "

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    external: true
  elasticsearch_data:
    driver: local