version: '3.8'

services:
  # Frontend service
  frontend:
    image: kahaozeng/prestabanco-frontend:latest
    container_name: frontend-1
    ports:
      - "8070:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend service
  backend:
    image: kahaozeng/prestabanco-backend:latest
    container_name: backend-1
    environment:
      DB_HOST: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prestabanco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - app-network

  # PostgreSQL 
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_DB: prestabanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - indices.query.bool.max_clause_count=10000
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana-1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network

  # Logstash ULTRA simplificado para tiempo real
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash-1
    ports:
      - "5514:5514/udp"
      - "5515:5515/tcp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      PIPELINE_WORKERS: 1
    depends_on:
      - elasticsearch
    networks:
      - app-network
    command: >
      bash -c "
      echo 'input { 
        tcp { port => 5515 codec => json }
        udp { port => 5514 codec => json }
      }
      filter {
        mutate { 
          add_field => { \"[@metadata][index]\" => \"prestabanco-realtime-%{+YYYY.MM.dd}\" }
          add_field => { \"application\" => \"prestabanco\" }
        }
        if [container_name] =~ /frontend/ {
          mutate { add_field => { \"service\" => \"frontend\" } }
        }
        if [container_name] =~ /backend/ {
          mutate { add_field => { \"service\" => \"backend\" } }
        }
      }
      output {
        elasticsearch {
          hosts => [\"elasticsearch:9200\"]
          index => \"%{[@metadata][index]}\"
        }
        stdout { codec => dots }
      }' > /usr/share/logstash/pipeline/logstash.conf &&
      /usr/local/bin/docker-entrypoint
      "

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    external: true
  elasticsearch_data:
    driver: local