version: '3'

services:
  # Frontend service
  frontend:
    image: kahaozeng/prestabanco-frontend:latest
    container_name: frontend-1
    ports:
      - "8070:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend service
  backend:
    image: kahaozeng/prestabanco-backend:latest
    container_name: backend-1
    environment:
      DB_HOST: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prestabanco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - app-network

  # PostgreSQL 
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_DB: prestabanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    external: true