# Removido version: '3.8' ya que es obsoleto en Docker Compose v2

services:
  # PostgreSQL - Sin logging especial
  postgres:
    image: postgres:latest
    container_name: postgres-1
    environment:
      POSTGRES_DB: prestabanco
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "0.0.0.0:5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch-1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Logstash - DEBE estar completamente listo antes que frontend/backend
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: logstash-1
    ports:
      - "12201:12201/udp"
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ul | grep :12201 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 90s
    command: >
      bash -c "
      cat > /usr/share/logstash/pipeline/logstash.conf << 'EOF'
      input {
        gelf {
          port => 12201
          codec => json
        }
        tcp {
          port => 5000
          codec => json
        }
      }
      
      filter {
        # Debug: mostrar todos los campos recibidos
        ruby {
          code => 'logger.info(\"Received event from: #{event.get(\"[host]\")} - #{event.get(\"[tag]\")}\", :event => event.to_hash)'
        }
        
        # Procesar tags de Docker
        if [tag] =~ /prestabanco\.frontend/ {
          mutate {
            add_field => { \"service\" => \"frontend\" }
            add_field => { \"app_type\" => \"nginx\" }
          }
        }
        if [tag] =~ /prestabanco\.backend/ {
          mutate {
            add_field => { \"service\" => \"backend\" }
            add_field => { \"app_type\" => \"spring-boot\" }
          }
        }
        
        # Agregar metadata
        mutate {
          add_field => { \"application\" => \"prestabanco\" }
          add_field => { \"environment\" => \"development\" }
          add_field => { \"received_at\" => \"%{@timestamp}\" }
        }
        
        # Asegurar timestamp
        if ![\"@timestamp\"] {
          ruby {
            code => 'event.set(\"@timestamp\", Time.now)'
          }
        }
      }
      
      output {
        elasticsearch {
          hosts => [\"elasticsearch:9200\"]
          index => \"prestabanco-docker-logs-%{+YYYY.MM.dd}\"
          template_overwrite => true
        }
        
        stdout { 
          codec => rubydebug {
            metadata => true
          }
        }
      }
      EOF
      
      echo 'Iniciando Logstash...'
      /usr/local/bin/docker-entrypoint
      "

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: kibana-1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - app-network

  # Backend - CON dependencia estricta en Logstash
  backend:
    image: kahaozeng/prestabanco-backend:latest
    container_name: backend-1
    environment:
      DB_HOST: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/prestabanco
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    ports:
      - "8090:8090"
    depends_on:
      postgres:
        condition: service_started
      logstash:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:12201"
        tag: "prestabanco.backend"
        gelf-compression-type: "none"
        gelf-compression-level: "1"
    restart: unless-stopped

  # Frontend - CON dependencia estricta en Logstash Y Backend
  frontend:
    image: kahaozeng/prestabanco-frontend:latest
    container_name: frontend-1
    ports:
      - "8070:80"
    depends_on:
      backend:
        condition: service_started
      logstash:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:12201"
        tag: "prestabanco.frontend"
        gelf-compression-type: "none"
        gelf-compression-level: "1"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    external: true
  elasticsearch_data:
    driver: local